-- PriceTruth PostgreSQL baseline for Netlify Database.
-- Runtime code never mutates schema; Netlify applies this file before publish.

CREATE TABLE schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at TEXT NOT NULL
);

CREATE TABLE accounts (
  email TEXT PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  plan TEXT NOT NULL DEFAULT 'free',
  stripe_customer TEXT,
  email_verified INTEGER NOT NULL DEFAULT 0,
  verified_at TEXT,
  deleted_at TEXT,
  billing_customer_hash TEXT,
  email_suppressed_at TEXT,
  email_suppression_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_accounts_stripe_unique
  ON accounts(stripe_customer) WHERE stripe_customer IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE products (
  id TEXT PRIMARY KEY,
  vertical TEXT NOT NULL,
  name TEXT NOT NULL,
  url TEXT,
  advertised_cents INTEGER NOT NULL,
  context_json TEXT NOT NULL DEFAULT '{}',
  source TEXT,
  source_label TEXT,
  certainty TEXT,
  fetched_at TEXT,
  evidence_json TEXT NOT NULL DEFAULT '{}',
  updated_at TEXT,
  visibility TEXT NOT NULL DEFAULT 'curated',
  owner_account_id TEXT REFERENCES accounts(id),
  created_at TEXT NOT NULL,
  CONSTRAINT products_private_owner CHECK (visibility <> 'private' OR owner_account_id IS NOT NULL),
  CONSTRAINT products_context_json_object CHECK (COALESCE(jsonb_typeof(context_json::jsonb) = 'object', FALSE)),
  CONSTRAINT products_evidence_json_object CHECK (COALESCE(jsonb_typeof(evidence_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_products_owner ON products(owner_account_id, visibility);

CREATE TABLE price_points (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ts TEXT NOT NULL,
  advertised_cents INTEGER NOT NULL,
  true_cents INTEGER NOT NULL,
  source TEXT,
  source_label TEXT,
  certainty TEXT,
  observed INTEGER NOT NULL DEFAULT 0,
  alert_eligible INTEGER NOT NULL DEFAULT 0,
  fetched_at TEXT,
  evidence_json TEXT NOT NULL DEFAULT '{}',
  provider_key TEXT,
  CONSTRAINT price_points_evidence_json_object CHECK (COALESCE(jsonb_typeof(evidence_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_pp_product_ts ON price_points(product_id, ts);
CREATE UNIQUE INDEX idx_pp_observation_unique ON price_points(
  product_id, ts, COALESCE(source, ''), COALESCE(provider_key, ''), advertised_cents, true_cents
);

CREATE TABLE alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  account_id TEXT REFERENCES accounts(id),
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  threshold_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  updated_at TEXT,
  last_notified_at TEXT,
  last_trigger_key TEXT,
  unsubscribe_token_hash TEXT,
  condition_active INTEGER NOT NULL DEFAULT 0,
  last_evaluated_cents INTEGER,
  last_delivered_trigger_key TEXT,
  quota_slot INTEGER,
  created_at TEXT NOT NULL,
  CONSTRAINT alerts_quota_slot_range CHECK (quota_slot IS NULL OR quota_slot BETWEEN 1 AND 20)
);

CREATE INDEX idx_alerts_account ON alerts(account_id, status);
-- A slot is the database-enforced alert quota. It makes the 1/20-account
-- limit exact across concurrent Function instances without relying on a
-- process lock or a read-then-insert count.
CREATE UNIQUE INDEX idx_alerts_account_quota_slot ON alerts(account_id, quota_slot)
  WHERE account_id IS NOT NULL AND status <> 'deleted';

CREATE TABLE api_keys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash TEXT NOT NULL UNIQUE,
  prefix TEXT,
  label TEXT NOT NULL,
  tier TEXT NOT NULL DEFAULT 'starter',
  owner_email TEXT,
  owner_account_id TEXT REFERENCES accounts(id),
  stripe_ref TEXT,
  last_used_at TEXT,
  revoked_at TEXT,
  replaced_by_id INTEGER REFERENCES api_keys(id),
  updated_at TEXT,
  can_write_history INTEGER NOT NULL DEFAULT 0,
  suspended INTEGER NOT NULL DEFAULT 0,
  revoked INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_keys_account ON api_keys(owner_account_id, revoked);

CREATE TABLE api_usage (
  key_id INTEGER NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(key_id, day)
);

-- Owned API keys share one exact daily counter. This avoids quota races when
-- an account uses multiple keys concurrently on separate Function instances.
CREATE TABLE account_api_usage (
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(account_id, day)
);

CREATE TABLE billing_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TEXT NOT NULL,
  type TEXT NOT NULL,
  email TEXT,
  account_id TEXT REFERENCES accounts(id),
  plan TEXT,
  amount_cents INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'usd',
  livemode INTEGER NOT NULL DEFAULT 0,
  stripe_ref TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'applied',
  payload_json TEXT NOT NULL DEFAULT '{}',
  CONSTRAINT billing_events_payload_json_object CHECK (COALESCE(jsonb_typeof(payload_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_billing_ts ON billing_events(ts);

CREATE TABLE pending_keys (
  session_id TEXT PRIMARY KEY,
  raw_key TEXT NOT NULL,
  tier TEXT NOT NULL,
  account_id TEXT REFERENCES accounts(id),
  key_iv TEXT,
  key_tag TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE auth_tokens (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  quota_slot INTEGER,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  created_at TEXT NOT NULL,
  CONSTRAINT auth_tokens_quota_slot_range CHECK (quota_slot IS NULL OR quota_slot BETWEEN 1 AND 5)
);

CREATE INDEX idx_auth_account ON auth_tokens(account_id, purpose, created_at);
CREATE UNIQUE INDEX idx_auth_tokens_active_quota_slot ON auth_tokens(account_id, purpose, quota_slot)
  WHERE consumed_at IS NULL AND quota_slot IS NOT NULL;

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  csrf_hash TEXT NOT NULL,
  user_agent_hash TEXT,
  ip_hash TEXT,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  revoked_at TEXT
);

CREATE INDEX idx_sessions_account ON sessions(account_id, expires_at);

CREATE TABLE account_preferences (
  account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  email_alerts INTEGER NOT NULL DEFAULT 1,
  weekly_digest INTEGER NOT NULL DEFAULT 0,
  timezone TEXT NOT NULL DEFAULT 'UTC',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE account_terms_acceptances (
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  terms_version TEXT NOT NULL,
  accepted_at TEXT NOT NULL,
  context_json TEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY(account_id, terms_version),
  CONSTRAINT account_terms_acceptances_context_json_object CHECK (COALESCE(jsonb_typeof(context_json::jsonb) = 'object', FALSE))
);

CREATE TABLE watchlist (
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(account_id, product_id)
);

CREATE TABLE notification_subscriptions (
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  verify_token_hash TEXT UNIQUE,
  unsubscribe_token_hash TEXT UNIQUE,
  verify_expires_at TEXT,
  verified_at TEXT,
  unsubscribed_at TEXT,
  bounced_at TEXT,
  complaint_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(account_id, channel)
);

CREATE TABLE notification_unsubscribe_tokens (
  token_hash TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_notification_unsubscribe_account
  ON notification_unsubscribe_tokens(account_id, channel, expires_at);

CREATE TABLE alert_unsubscribe_tokens (
  token_hash TEXT PRIMARY KEY,
  alert_id INTEGER NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_alert_unsubscribe_alert ON alert_unsubscribe_tokens(alert_id, expires_at);

CREATE TABLE outbox (
  id TEXT PRIMARY KEY,
  account_id TEXT REFERENCES accounts(id),
  to_email TEXT NOT NULL,
  template TEXT NOT NULL,
  payload_ciphertext TEXT NOT NULL,
  payload_iv TEXT NOT NULL,
  payload_tag TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  available_at TEXT NOT NULL,
  leased_until TEXT,
  lease_token TEXT,
  last_error TEXT,
  provider_message_id TEXT,
  idempotency_key TEXT UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  sent_at TEXT,
  CONSTRAINT outbox_metadata_json_object CHECK (COALESCE(jsonb_typeof(metadata_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_outbox_ready ON outbox(status, available_at, leased_until);

CREATE TABLE delivery_events (
  id TEXT PRIMARY KEY,
  outbox_id TEXT REFERENCES outbox(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  provider_event_id TEXT UNIQUE,
  provider_message_id TEXT,
  type TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  occurred_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  CONSTRAINT delivery_events_payload_json_object CHECK (COALESCE(jsonb_typeof(payload_json::jsonb) = 'object', FALSE))
);

CREATE TABLE jobs (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  available_at TEXT NOT NULL,
  leased_until TEXT,
  lease_token TEXT,
  last_error TEXT,
  idempotency_key TEXT UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT,
  CONSTRAINT jobs_payload_json_object CHECK (COALESCE(jsonb_typeof(payload_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_jobs_ready ON jobs(status, available_at, leased_until);

CREATE TABLE entitlements (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id),
  product TEXT NOT NULL,
  status TEXT NOT NULL,
  source TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  current_period_end TEXT,
  cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  provider_event_created BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(source, source_ref, product),
  CONSTRAINT entitlements_metadata_json_object CHECK (COALESCE(jsonb_typeof(metadata_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_entitlements_account ON entitlements(account_id, status);

CREATE TABLE billing_source_state (
  account_id TEXT NOT NULL REFERENCES accounts(id),
  source_ref TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_event_created BIGINT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(account_id, source_ref)
);

CREATE TABLE checkout_claims (
  session_id TEXT PRIMARY KEY,
  account_id TEXT REFERENCES accounts(id),
  plan TEXT NOT NULL,
  tier TEXT,
  status TEXT NOT NULL,
  claimed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_checkout_claims_account ON checkout_claims(account_id, status);

CREATE TABLE checkout_intents (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  plan TEXT NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  stripe_session_id TEXT,
  checkout_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  expires_at TEXT,
  payment_status TEXT,
  terms_version TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_checkout_intents_pending ON checkout_intents(account_id)
  WHERE status IN ('pending', 'awaiting_payment');

CREATE TABLE billing_reconciliation (
  event_id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  reason TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  resolved_at TEXT,
  CONSTRAINT billing_reconciliation_payload_json_object CHECK (COALESCE(jsonb_typeof(payload_json::jsonb) = 'object', FALSE))
);

CREATE INDEX idx_billing_reconciliation_status ON billing_reconciliation(status, updated_at);

CREATE TABLE provider_usage (
  day TEXT NOT NULL,
  provider TEXT NOT NULL,
  calls INTEGER NOT NULL DEFAULT 0,
  failures INTEGER NOT NULL DEFAULT 0,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  circuit_open_until TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(day, provider)
);

-- Durable rate buckets replace process-local security/account quotas where
-- exact cross-instance enforcement is required.
CREATE TABLE durable_rate_limits (
  bucket TEXT PRIMARY KEY,
  tokens DOUBLE PRECISION NOT NULL,
  updated_at_ms BIGINT NOT NULL,
  expires_at TEXT NOT NULL
);

INSERT INTO schema_migrations(version, name, applied_at)
VALUES (4, 'netlify-postgres-baseline', '2026-08-26T00:00:00.000Z');
