import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { isPublicHostname } from '../src/security.js';

const ROOT = path.resolve(import.meta.dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const DEFAULT_OUTPUT_DIR = path.join(ROOT, 'dist', 'netlify');
const LOCAL_SITE_ORIGIN = 'http://localhost:4780';

function normalizeSiteOrigin(value, { allowLocal = false, name = 'PRICETRUTH_SITE_ORIGIN or Netlify URL' } = {}) {
  const raw = String(value || '').trim();
  if (!raw) {
    throw new Error(`${name} is required and must be an origin-only URL.`);
  }
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`${name} must be a valid origin-only URL.`);
  }
  const localHost = ['localhost', '127.0.0.1', '::1', '[::1]'].includes(url.hostname);
  const publicHttps = url.protocol === 'https:' && isPublicHostname(url.hostname);
  const localHttp = allowLocal && url.protocol === 'http:' && localHost;
  if ((!publicHttps && !localHttp) || url.username || url.password ||
      (url.pathname !== '' && url.pathname !== '/') || url.search || url.hash) {
    throw new Error(`${name} must be a public origin-only HTTPS URL${allowLocal ? ' (or an HTTP localhost origin for local development)' : ''} with no credentials, path, query, or fragment.`);
  }
  return url.origin;
}

function redirectManifest() {
  return [
    '# Generated by scripts/build-netlify.mjs. Do not edit the build artifact.',
    '# Native Netlify Functions claim dynamic paths before these static fallbacks.',
    '# Unsupported methods on exact POST-only routes must never reach the SPA.',
    '/api/billing/webhook   /api-route-not-found.json            404',
    '/api/email/webhook     /api-route-not-found.json            404',
    '/api/internal/worker   /api-route-not-found.json            404',
    '/admin                 /admin.html                         200',
    '/admin/                /admin.html                         200',
    '/*                     /index.html                         200',
    '',
  ].join('\n');
}

const CANONICAL_ROUTES = ['/', '/find', '/analyze', '/compare', '/pricing', '/api-docs', '/extension', '/legal.html'];

function escapeAttribute(value) {
  return String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function injectCanonicalMeta(html, canonicalUrl) {
  const safeUrl = escapeAttribute(canonicalUrl);
  const canonical = `<link rel="canonical" href="${safeUrl}">`;
  const openGraph = `<meta property="og:url" content="${safeUrl}">`;
  let output = /<link\s+rel=["']canonical["'][^>]*>/i.test(html)
    ? html.replace(/<link\s+rel=["']canonical["'][^>]*>/i, canonical)
    : html.replace('</head>', `  ${canonical}\n</head>`);
  output = /<meta\s+property=["']og:url["'][^>]*>/i.test(output)
    ? output.replace(/<meta\s+property=["']og:url["'][^>]*>/i, openGraph)
    : output.replace('</head>', `  ${openGraph}\n</head>`);
  return output;
}

function robotsText(siteOrigin) {
  return `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /go/\nDisallow: /admin\nDisallow: /account\nDisallow: /billing/\nDisallow: /download/\n\nSitemap: ${siteOrigin}/sitemap.xml\n`;
}

function sitemapText(siteOrigin) {
  const entries = CANONICAL_ROUTES.map((route) => `  <url><loc>${siteOrigin}${route}</loc></url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
}

function safeOutputDirectory(outputDir) {
  const resolved = path.resolve(outputDir);
  const allowedRoots = [path.join(ROOT, 'dist') + path.sep, path.resolve(os.tmpdir()) + path.sep];
  if (!allowedRoots.some((prefix) => resolved.startsWith(prefix))) {
    throw new Error(`refusing to replace unsafe Netlify output directory: ${resolved}`);
  }
  return resolved;
}

function buildNetlify({
  siteOrigin = process.env.PRICETRUTH_SITE_ORIGIN || process.env.URL || LOCAL_SITE_ORIGIN,
  outputDir = DEFAULT_OUTPUT_DIR,
  allowLocal = !process.env.URL && !process.env.NETLIFY,
} = {}) {
  const publicOrigin = normalizeSiteOrigin(siteOrigin, { allowLocal });
  const destination = safeOutputDirectory(outputDir);

  fs.rmSync(destination, { recursive: true, force: true });
  fs.mkdirSync(destination, { recursive: true });
  fs.cpSync(PUBLIC_DIR, destination, { recursive: true });
  fs.writeFileSync(path.join(destination, '_redirects'), redirectManifest(), 'utf8');
  fs.writeFileSync(
    path.join(destination, 'api-route-not-found.json'),
    `${JSON.stringify({ error: 'not found', code: 'NOT_FOUND' })}\n`,
    'utf8',
  );
  fs.writeFileSync(path.join(destination, 'robots.txt'), robotsText(publicOrigin), 'utf8');
  fs.writeFileSync(path.join(destination, 'sitemap.xml'), sitemapText(publicOrigin), 'utf8');

  const appShell = fs.readFileSync(path.join(PUBLIC_DIR, 'index.html'), 'utf8');
  for (const route of CANONICAL_ROUTES) {
    if (route === '/legal.html') {
      const legalPath = path.join(destination, 'legal.html');
      fs.writeFileSync(legalPath, injectCanonicalMeta(fs.readFileSync(legalPath, 'utf8'), `${publicOrigin}${route}`), 'utf8');
      continue;
    }
    const target = route === '/' ? path.join(destination, 'index.html') : path.join(destination, route.slice(1), 'index.html');
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, injectCanonicalMeta(appShell, `${publicOrigin}${route}`), 'utf8');
  }

  console.log(`Netlify bundle ready: ${path.relative(ROOT, destination)}`);
  console.log(`Public site origin: ${publicOrigin}`);
  console.log('Dynamic routes are handled by native Netlify Functions on the same origin.');
  return { destination, siteOrigin: publicOrigin };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    buildNetlify();
  } catch (error) {
    console.error(`NETLIFY BUILD FAILED: ${error.message}`);
    process.exit(1);
  }
}

export {
  buildNetlify, normalizeSiteOrigin, redirectManifest, safeOutputDirectory,
  injectCanonicalMeta, robotsText, sitemapText,
};
